### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [sanaltsk/codepath-simpletweet#1]
@sanaltsk : The requirement User is displayed the username, name, and body for each tweet is incomplete. Please complete and update status here /cc @codepathreview

**Comment by sanaltsk** [comment]
Hi @codepathreview 

Apologies on missing out the username in timeline. I have add the change and pushed the code back.

https://i.imgur.com/NdRMa4K.gif

Thanks,
Sanal

**Comment by sanaltsk** [comment]
Hi,

Apologies on missing out the username in timeline. I have add the change
and pushed the code back.

https://i.imgur.com/NdRMa4K.gif

https://github.com/sanaltsk/codepath-simpletweet/commit/e14099fcb4577b0672ba2c83da25b3220a2d2a81

Thanks,
Sanal
